version: '2'

services:
    frontserver:
        image: php:7.1-cli
        working_dir: /var/www/html
        entrypoint: /bin/bash -c /var/www/html/opt/app/entrypoint.sh
        volumes:
            - .:/var/www/html
        ports:
          - 8080:8080
          - 8443:8443
